// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vHghvXSF0gSDAE3NcEic5Q88dK3XRVc',
    appId: '1:849203660911:web:42f87d9e72bf06c78f259a',
    messagingSenderId: '849203660911',
    projectId: 'authflutter-4a622',
    authDomain: 'authflutter-4a622.firebaseapp.com',
    storageBucket: 'authflutter-4a622.appspot.com',
    measurementId: 'G-9SW7CY7T48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_iXsJb81VObu5IuyN_GKxTHvbldIwFi4',
    appId: '1:849203660911:android:9cf35b0ee2f20d238f259a',
    messagingSenderId: '849203660911',
    projectId: 'authflutter-4a622',
    storageBucket: 'authflutter-4a622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUZxJ-2m-8Q-XoP9Y9GFaoHbsNNgqCQp0',
    appId: '1:849203660911:ios:defea48fe3e620268f259a',
    messagingSenderId: '849203660911',
    projectId: 'authflutter-4a622',
    storageBucket: 'authflutter-4a622.appspot.com',
    iosBundleId: 'com.example.authenticationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUZxJ-2m-8Q-XoP9Y9GFaoHbsNNgqCQp0',
    appId: '1:849203660911:ios:b615e7e79f0a78ec8f259a',
    messagingSenderId: '849203660911',
    projectId: 'authflutter-4a622',
    storageBucket: 'authflutter-4a622.appspot.com',
    iosBundleId: 'com.example.authenticationFlutter.RunnerTests',
  );
}
